-- MySQL Script generated by MySQL Workbench
-- 08/12/17 23:19:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema crm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crm` DEFAULT CHARACTER SET utf8 ;
USE `crm` ;

-- -----------------------------------------------------
-- Table `crm`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_type` VARCHAR(45) NULL,
  `employee_fname` VARCHAR(45) NULL,
  `employee_mname` VARCHAR(45) NULL,
  `employee_lname` VARCHAR(45) NULL,
  `employee_contact_number` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `template_type` VARCHAR(45) NULL,
  `template_description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_checkin` VARCHAR(45) NULL,
  `customer_checkout` VARCHAR(45) NULL,
  `customer_numberdays` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`recipient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`recipient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `recipient_type` VARCHAR(45) NULL,
  `recipient_email` VARCHAR(45) NULL,
  `recipient_fname` VARCHAR(45) NULL,
  `recipient_mname` VARCHAR(45) NULL,
  `recipient_lname` VARCHAR(45) NULL,
  `recipient_contact_number` BIGINT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recipient_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_recipient_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `crm`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`email` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email_date` DATE NULL,
  `email_recipient` VARCHAR(45) NULL,
  `email_template` VARCHAR(45) NULL,
  `email_status` VARCHAR(45) NULL,
  `template_id` INT NOT NULL,
  `recipient_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_email_template1_idx` (`template_id` ASC),
  INDEX `fk_email_recipient1_idx` (`recipient_id` ASC),
  CONSTRAINT `fk_email_template1`
    FOREIGN KEY (`template_id`)
    REFERENCES `crm`.`template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_email_recipient1`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `crm`.`recipient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`Existing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`Existing` (
  `customer_ID` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`customer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`webvisit_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`webvisit_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wvh_date` DATE NULL,
  `wvh_time` DATETIME NULL,
  `wvh_ip_address` VARCHAR(20) NULL,
  `wvh_url` VARCHAR(100) NULL,
  `wvh_cookie_information` VARCHAR(45) NULL,
  `recipient_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_webvisit_history_recipient1_idx` (`recipient_id` ASC),
  CONSTRAINT `fk_webvisit_history_recipient1`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `crm`.`recipient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_date_created` DATETIME NULL,
  `event_description` VARCHAR(400) NULL,
  `event_start_date` DATE NULL,
  `event_end_date` DATE NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_event_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_event_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `crm`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`preference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`preference` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preference_category` VARCHAR(45) NULL,
  `preference_description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`activity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `activity_status` VARCHAR(45) NULL,
  `activity_description` VARCHAR(45) NULL,
  `email_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_activity_email1_idx` (`email_id` ASC),
  CONSTRAINT `fk_activity_email1`
    FOREIGN KEY (`email_id`)
    REFERENCES `crm`.`email` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`email_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`email_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_id` INT NOT NULL,
  `email_id` INT NOT NULL,
  INDEX `fk_event_has_email_email1_idx` (`email_id` ASC),
  INDEX `fk_event_has_email_event1_idx` (`event_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_event_has_email_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `crm`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_has_email_email1`
    FOREIGN KEY (`email_id`)
    REFERENCES `crm`.`email` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`recipient_preference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`recipient_preference` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `recipient_id` INT NOT NULL,
  `preference_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_preference_has_recipient_recipient1_idx` (`recipient_id` ASC),
  INDEX `fk_preference_has_recipient_preference1_idx` (`preference_id` ASC),
  CONSTRAINT `fk_preference_has_recipient_preference1`
    FOREIGN KEY (`preference_id`)
    REFERENCES `crm`.`preference` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preference_has_recipient_recipient1`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `crm`.`recipient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
